service: whatsup
image: alexohneander/whatsup
servers:
  web:
    hosts: 142.132.160.251
    traefik: true
    labels:
      traefik.http.routers.whatsup.entrypoints: websecure
      traefik.http.routers.whatsup.rule: Host(`whatsup.kamal.wellcom.rocks`)
      traefik.http.routers.whatsup.tls: true
      traefik.http.routers.whatsup.tls.certresolver: letsencrypt
  worker:
    traefik: false
    hosts: 142.132.160.251
    cmd: bundle exec sidekiq
volumes:
  - "/var/lib/whatsup/storage:/rails/storage"
registry:
  username: alexohneander
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  REDIS_URL: redis://whatsup-redis:6379/4
  secret:
    - RAILS_MASTER_KEY
builder:
  cache:
    type: registry
traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    certificatesResolvers.letsencrypt.acme.email: "moin@wellnitz-alex.de"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web
    accesslog: true
accessories:
  redis:
    host: 142.132.160.251
    image: redis:latest
    port: "6379:6379"
    volumes:
      - /var/lib/redis:/data
